-- 016_payment_orders_cohorts_webhook.sql
-- Persistence thanh toán Breakout: payment_orders (bền qua redeploy, fix bug K3 mất 7 VIP),
-- cohorts (SSOT cohort), webhook_events (idempotency/audit SePay).
-- Idempotent (IF NOT EXISTS): production đã có sẵn 3 bảng này (tạo ad-hoc), migration này
-- đưa schema vào repo cho reproducibility. KHÔNG phá dữ liệu prod.
-- Khớp cột với breakout/webapp/backend/app.py (INSERT INTO breakoutos.payment_orders).

CREATE SCHEMA IF NOT EXISTS breakoutos;

-- ---------- cohorts ----------
CREATE TABLE IF NOT EXISTS breakoutos.cohorts (
  cohort_id            text PRIMARY KEY,
  name                 text NOT NULL,
  day1_at              timestamptz,
  day2_at              timestamptz,
  day3_at              timestamptz,
  foundation_close_at  timestamptz,
  products             jsonb NOT NULL DEFAULT '{}'::jsonb,
  sender_email         text,
  sender_name          text,
  reply_to             text,
  status               text NOT NULL DEFAULT 'active',
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

-- ---------- payment_orders ----------
CREATE TABLE IF NOT EXISTS breakoutos.payment_orders (
  order_code             text PRIMARY KEY,
  product                text NOT NULL,
  product_name           text NOT NULL,
  amount_vnd             bigint NOT NULL,
  tag                    text NOT NULL,
  stage_id               text,
  email                  text NOT NULL,
  phone                  text,
  name                   text,
  status                 text NOT NULL,
  paid_at                timestamptz,
  refunded_at            timestamptz,
  refund_reason          text,
  sepay_payload          jsonb,
  sepay_transaction_id   text,
  sepay_reference        text,
  ghl_tag_result         jsonb,
  ghl_stage_move_result  jsonb,
  ghl_contact_id         text,
  success_redirect       text,
  cohort_id              text,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now(),
  order_json             jsonb
);
CREATE INDEX IF NOT EXISTS payment_orders_cohort_idx ON breakoutos.payment_orders (cohort_id);
CREATE INDEX IF NOT EXISTS payment_orders_status_idx ON breakoutos.payment_orders (status);

-- ---------- webhook_events (idempotency + audit) ----------
CREATE TABLE IF NOT EXISTS breakoutos.webhook_events (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source        text NOT NULL,
  event_type    text NOT NULL,
  external_id   text,
  payload       jsonb NOT NULL,
  headers       jsonb,
  received_at   timestamptz NOT NULL DEFAULT now(),
  processed_at  timestamptz,
  status        text NOT NULL DEFAULT 'received',
  result        jsonb,
  error         text,
  order_code    text
);
CREATE INDEX IF NOT EXISTS webhook_events_order_idx ON breakoutos.webhook_events (order_code);
CREATE UNIQUE INDEX IF NOT EXISTS webhook_events_source_external_uidx
  ON breakoutos.webhook_events (source, external_id) WHERE external_id IS NOT NULL;

-- ---------- seed cohort k4-2026-07 (19:00 VN = 12:00 UTC; đóng 22:00 VN = 15:00 UTC) ----------
INSERT INTO breakoutos.cohorts
  (cohort_id, name, day1_at, day2_at, day3_at, foundation_close_at, products, status)
VALUES (
  'k4-2026-07', 'Breakout Challenge K4',
  '2026-07-13T12:00:00Z', '2026-07-14T12:00:00Z', '2026-07-15T12:00:00Z',
  '2026-07-17T15:00:00Z',
  '{"vip": {"product": "abs-k4-vip", "amount_vnd": 199000, "tag": "venture-breakout-k4-vip"}}'::jsonb,
  'active'
)
ON CONFLICT (cohort_id) DO NOTHING;
