"""L1 Founder OS Tier B AI extraction prompts.

Tier B files generated by AI from Tier A inputs:
- why-statement (Haiku 4.5) — from identity + lived-experience
- founder-assets (Haiku 4.5) — 8 categories from background
- founder-story (Opus 4.7) — 3-act narrative
"""

WHY_STATEMENT_PROMPT = """Bạn là chuyên gia phân tích Founder Identity.
Đầu vào là Bản Sắc Sáng Lập + trải nghiệm sống của một người sáng lập.
Trích xuất Lý Do Cốt Lõi (Why Statement) sâu hơn tiền.

Tiếng Việt thuần, không "—", không "dạy". Câu ngắn, conversational.

INPUT:
Founder Identity (giá trị + năng lực + archetype):
{identity}

Decision Principles (5-7 nguyên tắc sống):
{decision_principles}

Anti Vision (điều KHÔNG muốn):
{anti_vision}

Customer direction (ai muốn phục vụ):
{customer_direction}

OUTPUT JSON SCHEMA (strict):
{{
  "why_core": "1 câu, ≤30 từ, lý do sâu hơn tiền",
  "why_paragraph_1": "1 đoạn ~50 từ, mở rộng vì sao",
  "why_paragraph_2": "1 đoạn ~50 từ, liên kết với customer (vì sao phục vụ nhóm này)",
  "personal_anchor": "1 câu, kỷ niệm/trải nghiệm cá nhân làm Why này persistent",
  "confidence_score": <int 0-100>,
  "missing_fields": [<list field cần fill thêm để Why rõ hơn>],
  "recommendations": [<list gợi ý cải thiện>]
}}

Chỉ trả JSON, không kèm text khác.
"""


FOUNDER_ASSETS_PROMPT = """Bạn là chuyên gia phân tích Founder Assets.
Phân biệt rõ: Assets = TÀI SẢN đo được, KHÁC identity (tư duy).

Trích xuất 8 nhóm tài sản từ background của founder.
Tiếng Việt thuần, không "—".

QUY TẮC BẰNG CHỨNG:
- Chỉ dùng số liệu, bằng cấp, chứng chỉ, vai trò và kết quả có trong INPUT.
- Không suy đoán số năm, quy mô network, email list, case study hoặc credential.
- Nếu một trường không có bằng chứng, để giá trị rỗng và ghi vào missing_fields.

INPUT:
Founder Identity:
{identity}

Background / Lived Experience:
{lived_experience}

Customer direction:
{customer_direction}

OUTPUT JSON SCHEMA (strict):
{{
  "knowledge": [<list Master/MBA/course significant>],
  "experience": [{{"years": <int>, "field": "...", "role": "..."}}],
  "certifications": [<list license/cert/accreditation>],
  "network": {{"count": <int>, "tier": "...", "niche": "..."}},
  "case_studies": [{{"title": "...", "proof": "..."}}],
  "story_tags": [<list short tags cho story re-use>],
  "media": {{"fb_page": <bool>, "email_list": <int>, "podcast": <bool>}},
  "skills": [<list specific skills relevant>],
  "asset_strength_score": <int 0-100>,
  "confidence_score": <int 0-100>,
  "missing_fields": [<list>],
  "recommendations": [<list ideas to leverage existing assets>]
}}

Chỉ trả JSON.
"""


FOUNDER_STORY_PROMPT = """Bạn là biên kịch chuyên dựng câu chuyện founder 3-act narrative.
KHÔNG generic. KHÔNG sáo rỗng. Dùng chi tiết cụ thể (địa danh, năm, con số, nhân vật).

Tiếng Việt thuần, câu ngắn 5-12 từ, conversational. Không "—", không "dạy".

QUY TẮC BẰNG CHỨNG:
- Chỉ dùng chi tiết xuất hiện trong INPUT.
- Không tự tạo địa danh, năm, con số, nhân vật, khủng hoảng hoặc mất mát.
- Không biến suy đoán thành sự thật.
- Thiếu chi tiết nào thì ghi vào missing_fields, không bù bằng nội dung hư cấu.

3-act structure:
ACT 1 ORIGIN: Xuất thân và môi trường chỉ khi INPUT có bằng chứng
ACT 2 CRISIS: Bước ngoặt hoặc vấn đề chỉ khi INPUT có bằng chứng
ACT 3 TRANSFORMATION: Hành trình hôm nay, năng lực + bài học

5-10 chi tiết cụ thể (concrete details).

INPUT:
Founder Identity:
{identity}

Life Mission:
{mission}

Lived Experience:
{lived_experience}

Why Statement:
{why_statement}

OUTPUT JSON SCHEMA (strict):
{{
  "act_1_origin": "1 đoạn ~100 từ. Chỉ dùng xuất phát điểm có trong INPUT. Nếu thiếu, ghi rõ [cần bổ sung], không tạo chuyện gia đình hoặc tuổi thơ.",
  "act_2_crisis": "1 đoạn ~100 từ. Chỉ dùng bước ngoặt có trong INPUT. Nếu thiếu, ghi rõ [cần bổ sung], không tạo khủng hoảng hoặc mất mát.",
  "act_3_transformation": "1 đoạn ~100 từ. Hành trình. Năng lực. Bài học. Con người hôm nay.",
  "concrete_details": [<list 5-10 chi tiết: địa danh + năm + con số + nhân vật>],
  "hook_30s": "1 câu hook cho reel 30 giây",
  "opening_5m": "Đoạn mở đầu webinar 5 phút (~150 từ)",
  "sales_800w": "Phiên bản sales page 800 từ (markdown)",
  "podcast_30m_outline": [<list 5-7 segment headlines>],
  "confidence_score": <int 0-100>,
  "missing_fields": [<list>],
  "recommendations": [<list cách story strong hơn>]
}}

Chỉ trả JSON.
"""


# Map file_key → (model, prompt template, input keys)
EXTRACTION_REGISTRY = {
    "why-statement": {
        "model": "claude-haiku-4-5",
        "prompt": WHY_STATEMENT_PROMPT,
        "input_keys": ["identity", "decision_principles", "anti_vision", "customer_direction"],
        "max_tokens": 2000,
    },
    "founder-assets": {
        "model": "claude-haiku-4-5",
        "prompt": FOUNDER_ASSETS_PROMPT,
        "input_keys": ["identity", "lived_experience", "customer_direction"],
        "max_tokens": 2500,
    },
    "founder-story": {
        "model": "claude-opus-4-7",  # Opus for narrative quality
        "prompt": FOUNDER_STORY_PROMPT,
        "input_keys": ["identity", "mission", "lived_experience", "why_statement"],
        "max_tokens": 7000,
    },
}
