"""
capstone_spawn.py — BreakoutOS v3 Sprint 3

Spawn 1 AIOS instance riêng cho mỗi student sau khi hoàn thành 10 tuần BreakoutOS.

Capstone deliverable cuối cùng: 1 mini-AIOS chứa kernel + 5 config files của student,
deploy thành Railway service riêng với custom subdomain.

Approach:
    Pattern "1 Kernel + 5 config" giống `breakoutos.md` v1.
    - 5 config files generated từ student data (voice, style, story, compliance, facts).
    - Railway service spawn từ template repo `camas-kernel-template` (forked, không có Anna config).
    - Cloudflare CNAME `{student_id}.aios.breakout.live` → new Railway service.
    - Magic link + email gửi credentials.

Cách dùng CLI:
    python tools/capstone_spawn.py --student-id linh-tran \
        --display-name "Lê Thị Linh" \
        --owner-email linh@example.com \
        --voice-register custom \
        --venture-slug breakout

Cách dùng programmatic:
    from tools.capstone_spawn import spawn_capstone_instance
    result = await spawn_capstone_instance(
        student_id="linh-tran",
        owner_email="linh@example.com",
        display_name="Lê Thị Linh",
        student_data={
            "vision": "...",
            "niche": "...",
            "customer_profile": {...},
            "offer": {...},
            "voice_register": "custom",
            "story_pool": ["..."],
            "industry_facts": {...}
        }
    )

Pre-requisites:
    - Migration 004 applied (capstone_instance table)
    - Railway API token (RAILWAY_API_TOKEN env)
    - GitHub repo `cohangai-camas-kernel-template` exists (forked from camas-kernel)
    - CLOUDFLARE_API_TOKEN + CLOUDFLARE_ZONE_ID_BREAKOUT set
    - BREVO_API_KEY for magic link email

KHÔNG bao gồm trong skeleton này (Anna setup manual):
    - Actual Railway service deploy (cần fork repo + Railway template setup)
    - Custom domain SSL provisioning (Railway auto, ~3 phút)
    - DB schema isolation per capstone instance (mỗi instance = 1 Postgres DB?)

Hiện trạng (2026-06-09):
    - skeleton code đầy đủ, ready khi Anna fork repo + setup Railway template
    - Generators 5 config file đầy đủ, test được offline (no Railway call)
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional

try:
    import asyncpg
except ImportError:
    asyncpg = None

try:
    import httpx
except ImportError:
    httpx = None

log = logging.getLogger("camas.capstone_spawn")
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")


# ─────────────────────────────────────────────────────────────
# Dataclasses
# ─────────────────────────────────────────────────────────────

@dataclass
class CapstoneInput:
    student_id: str
    owner_email: str
    display_name: str
    student_data: dict  # vision, niche, customer_profile, offer, voice_register, story_pool, industry_facts
    venture_slug: str = "breakout"
    custom_domain: Optional[str] = None
    fan_hub_tenant_id: Optional[str] = None  # link to Fan Hub spawn (if exist)
    dry_run: bool = False  # if True, generate configs only, không deploy Railway


@dataclass
class CapstoneResult:
    success: bool
    student_id: Optional[str] = None
    subdomain: Optional[str] = None
    custom_domain: Optional[str] = None
    railway_service_id: Optional[str] = None
    railway_service_name: Optional[str] = None
    admin_url: Optional[str] = None
    fan_hub_subdomain: Optional[str] = None
    config_files: dict = field(default_factory=dict)  # 5 generated files
    cname_created: bool = False
    email_sent: bool = False
    errors: list = field(default_factory=list)
    next_steps: list = field(default_factory=list)  # for Anna review


# ─────────────────────────────────────────────────────────────
# 5 Config Generators
# ─────────────────────────────────────────────────────────────

def generate_voice_profile_md(student_data: dict) -> str:
    """Generate voice_profile.md from Content Engine voice register + sample posts."""
    voice = student_data.get("voice_register", "default")
    vision = student_data.get("vision", "")
    niche = student_data.get("niche", "")

    sample_posts = student_data.get("sample_posts", [])
    sample_section = ""
    if sample_posts:
        sample_section = "\n\n## Sample posts (voice reference)\n\n"
        for i, post in enumerate(sample_posts[:5], 1):
            sample_section += f"### Post {i}\n{post}\n\n"

    return f"""# Voice Profile — {student_data.get("display_name", "Student")}

Generated by BreakoutOS v3 Capstone Spawn at {datetime.utcnow().isoformat()}

## Identity
- Name: {student_data.get("display_name", "Student")}
- Venture: {student_data.get("venture_slug", "breakout")}
- Niche: {niche}
- Vision: {vision}

## Voice register
- Base register: `{voice}`
- Tone descriptor: {student_data.get("voice_tone_descriptor", "Thực dụng, có số, không buzzword")}
- Language: Tiếng Việt thuần (no English mixed unless brand-specific)

## Tone rules
1. Câu ngắn 5-15 từ
2. Không dấu em-dash (em-dash literal "—")
3. Không emoji trừ khi explicit
4. Conversational, đọc to nghe tự nhiên
5. Có số cụ thể trong mọi claim
6. Bắt đầu từ khách hàng, không từ sản phẩm
7. Pause bằng `…`, không bằng dash

{sample_section}

## Banned phrases
- "khách hàng tiềm năng"
- "chuyển đổi cao"
- "tối ưu hoá"
- "đột phá"
- "tăng trưởng vượt bậc"
- "giải pháp toàn diện"

## Preferred patterns
- "Cụ thể là..."
- "Trong 30 ngày..."
- "Bạn có X, không có Y"
- Story → Lesson → CTA structure
"""


def generate_style_rules_md(student_data: dict) -> str:
    """Generate style_rules.md from offer + customer profile language patterns."""
    offer = student_data.get("offer", {})
    customer_profile = student_data.get("customer_profile", {})
    pain_points = customer_profile.get("pain_points", [])
    desired_outcomes = customer_profile.get("desired_outcomes", [])

    return f"""# Style Rules — {student_data.get("display_name", "Student")}

## Content style do's

1. Reference cụ thể nỗi đau khách hàng (pull từ customer profile)
2. Mỗi reel có 1 hook 6-10 từ
3. Mỗi email subject có 1 specific number hoặc concrete claim
4. CTA cụ thể, không "tìm hiểu thêm"
5. Story THẬT từ story pool, không bịa

## Content style don'ts

1. Không lecture mode
2. Không AI-sounding "thật tuyệt vời", "rất quan trọng"
3. Không listicle quá 7 items
4. Không over-promise

## Customer pain language (use these phrases)
{json.dumps(pain_points, ensure_ascii=False, indent=2) if pain_points else "(chưa có data)"}

## Customer outcome language
{json.dumps(desired_outcomes, ensure_ascii=False, indent=2) if desired_outcomes else "(chưa có data)"}

## Offer reference
- Core promise: {offer.get("core_promise", "")}
- Price: {offer.get("price", "")}
- Risk reversal: {offer.get("guarantee", "")}
- Timeline: {offer.get("timeline", "")}

## Headline patterns

1. "Cách [persona] [achieve outcome] trong [timeline]"
2. "[Number] điều [persona] không biết về [topic]"
3. "Tôi đã [transformation], đây là cách [proof element]"
"""


def generate_story_pool_json(student_data: dict) -> str:
    """Generate story_pool.json from stories collected during Content Engine."""
    story_pool = student_data.get("story_pool", [])

    structured_stories = []
    for i, story in enumerate(story_pool, 1):
        if isinstance(story, str):
            structured_stories.append({
                "id": f"S{i:02d}",
                "raw": story,
                "tags": [],
                "usable_for": ["reel", "fb_post", "email"],
                "public_safe": True
            })
        elif isinstance(story, dict):
            structured_stories.append({
                "id": story.get("id", f"S{i:02d}"),
                "raw": story.get("raw", ""),
                "tags": story.get("tags", []),
                "usable_for": story.get("usable_for", ["reel", "fb_post", "email"]),
                "public_safe": story.get("public_safe", True)
            })

    return json.dumps({
        "version": "1.0",
        "generated_at": datetime.utcnow().isoformat(),
        "student_id": student_data.get("student_id", ""),
        "story_count": len(structured_stories),
        "stories": structured_stories
    }, ensure_ascii=False, indent=2)


def generate_compliance_yaml(student_data: dict) -> str:
    """Generate compliance.yaml from venture industry + Anna master compliance."""
    venture = student_data.get("venture_slug", "breakout")
    industry = student_data.get("industry", "")

    base = f"""# Compliance Rules — {student_data.get("display_name", "Student")}
# Generated {datetime.utcnow().isoformat()}

venture: {venture}
industry: {industry}

# Hard rules (cấm tuyệt đối)
banned_claims:
  - pattern: "đảm bảo \\\\d+%"
    reason: "Không hứa kết quả cụ thể %"
  - pattern: "x\\\\d+ doanh thu"
    reason: "Không hứa multi-X revenue"
  - pattern: "thành công 100%"
    reason: "Không hứa thành công tuyệt đối"

banned_phrases:
  - "đột phá"
  - "khai phóng"
  - "tiên phong"
  - "duy nhất tại Việt Nam"
  - "hàng đầu Châu Á"

# Required elements
required_disclaimer_for:
  - financial_claims  # if mention specific income → add "kết quả không bảo đảm"
  - testimonial       # if quote customer → add "trường hợp cá nhân"

# Escalation triggers (cần human review)
escalate_if:
  - sensitive_topic_detected: ["sức khỏe", "y tế", "luật pháp", "tài chính cụ thể"]
  - public_figure_mentioned: true
  - competitor_compared_negatively: true
"""

    # Industry-specific overlays
    if "migration" in industry.lower() or venture == "migration":
        base += """
# Migration-specific (MARA compliance)
mara_compliance:
  - no_visa_success_rate_claim: true
  - no_specific_immigration_advice: true
  - require_disclaimer_for_general_info: "Đây là thông tin tham khảo, không phải tư vấn pháp lý"
"""

    if "health" in industry.lower() or "y tế" in industry.lower():
        base += """
# Health/medical-specific
health_compliance:
  - no_diagnostic_claim: true
  - no_specific_dose_recommendation: true
  - require_consult_doctor_disclaimer: true
"""

    return base


def generate_venture_facts_yaml(student_data: dict) -> str:
    """Generate venture_facts.yaml from offer + pricing + landing copy."""
    offer = student_data.get("offer", {})
    customer_profile = student_data.get("customer_profile", {})
    industry_facts = student_data.get("industry_facts", {})

    return f"""# Venture Facts — {student_data.get("display_name", "Student")}
# Canonical RAG seed for all agents. Update when changes.
# Generated {datetime.utcnow().isoformat()}

founder:
  name: "{student_data.get("display_name", "")}"
  email: "{student_data.get("owner_email", "")}"
  niche: "{student_data.get("niche", "")}"
  vision: "{student_data.get("vision", "")}"

venture:
  slug: "{student_data.get("venture_slug", "breakout")}"
  description: "{offer.get("core_promise", "")}"
  founded: "{datetime.utcnow().strftime("%Y-%m")}"
  industry: "{student_data.get("industry", "")}"

audience:
  primary_persona: "{customer_profile.get("primary_persona", "")}"
  age_range: "{customer_profile.get("age_range", "")}"
  location: "{customer_profile.get("location", "")}"
  pain_points:
{_yaml_list(customer_profile.get("pain_points", []))}
  desired_outcomes:
{_yaml_list(customer_profile.get("desired_outcomes", []))}

offer:
  product_name: "{offer.get("name", "")}"
  format: "{offer.get("format", "")}"
  duration: "{offer.get("duration", "")}"
  price_vnd: {offer.get("price_vnd", 0)}
  payment_methods: ["sepay_transfer", "vnpay"]
  delivery_method: "{offer.get("delivery_method", "")}"
  guarantee: "{offer.get("guarantee", "")}"

pricing_ladder:
  front_end:
    name: "{offer.get("front_end", {}).get("name", "")}"
    price_vnd: {offer.get("front_end", {}).get("price_vnd", 0)}
  core:
    name: "{offer.get("name", "")}"
    price_vnd: {offer.get("price_vnd", 0)}
  backend:
    name: "{offer.get("backend", {}).get("name", "")}"
    price_vnd: {offer.get("backend", {}).get("price_vnd", 0)}

policy:
  refund_days: 14
  refund_conditions: "{offer.get("refund_conditions", "Hoàn 100% nếu không hài lòng")}"
  delivery_sla: "Truy cập ngay sau thanh toán"

industry_facts:
{json.dumps(industry_facts, ensure_ascii=False, indent=2) if industry_facts else "  # Chưa có data"}

# Cập nhật mỗi quarter hoặc khi pricing/offer/policy thay đổi
"""


def _yaml_list(items: list) -> str:
    if not items:
        return "    []"
    return "\n".join([f'    - "{item}"' for item in items])


# ─────────────────────────────────────────────────────────────
# Core spawn function
# ─────────────────────────────────────────────────────────────

async def spawn_capstone_instance(
    student_id: str,
    owner_email: str,
    display_name: str,
    student_data: dict,
    venture_slug: str = "breakout",
    custom_domain: Optional[str] = None,
    fan_hub_tenant_id: Optional[str] = None,
    dry_run: bool = False,
) -> CapstoneResult:
    """Spawn Capstone AIOS instance.

    Steps:
      1. Validate input
      2. Generate 5 config files
      3. (dry_run) Save configs to local + return
      4. Insert capstone_instance row (status=spawning)
      5. Spawn Railway service from template repo
      6. Wait for healthcheck
      7. Setup CNAME at Cloudflare
      8. Send magic link email
      9. Update capstone_instance row (status=live)
      10. Return CapstoneResult
    """
    result = CapstoneResult(success=False, student_id=student_id)

    # Step 1: Validate
    student_id = (student_id or "").strip().lower()
    if not student_id or not all(c.isalnum() or c == "-" for c in student_id):
        result.errors.append("invalid student_id (alphanumeric + dash only)")
        return result

    if "@" not in owner_email:
        result.errors.append("invalid owner_email")
        return result

    # Step 2: Generate 5 config files
    student_data["student_id"] = student_id
    student_data["display_name"] = display_name
    student_data["owner_email"] = owner_email
    student_data["venture_slug"] = venture_slug

    configs = {
        "voice_profile.md": generate_voice_profile_md(student_data),
        "style_rules.md": generate_style_rules_md(student_data),
        "story_pool.json": generate_story_pool_json(student_data),
        "compliance.yaml": generate_compliance_yaml(student_data),
        "venture_facts.yaml": generate_venture_facts_yaml(student_data),
    }
    result.config_files = configs

    if dry_run:
        # Save to local for review
        out_dir = f"/tmp/capstone-{student_id}"
        os.makedirs(out_dir, exist_ok=True)
        for filename, content in configs.items():
            with open(os.path.join(out_dir, filename), "w", encoding="utf-8") as f:
                f.write(content)
        result.success = True
        result.subdomain = f"{student_id}.aios.breakout.live"
        result.custom_domain = custom_domain or result.subdomain
        result.next_steps.append(f"Configs saved to {out_dir} for review")
        result.next_steps.append("Anna review configs, then re-run with dry_run=False to actually spawn")
        log.info(f"Dry run: configs saved to {out_dir}")
        return result

    # Step 4: Insert capstone_instance row
    dsn = os.environ.get("DATABASE_URL")
    if not dsn or not asyncpg:
        result.errors.append("DATABASE_URL not set or asyncpg not installed")
        return result

    try:
        conn = await asyncpg.connect(dsn)
    except Exception as exc:
        result.errors.append(f"DB connect fail: {exc}")
        return result

    subdomain = f"{student_id}.aios.breakout.live"
    primary_domain = custom_domain or subdomain
    magic_link_token = str(uuid.uuid4())

    try:
        await conn.execute("""
            INSERT INTO capstone_instance (
                student_id, subdomain, custom_domain, fan_hub_subdomain, fan_hub_tenant_id,
                config_voice_profile, config_style_rules, config_story_pool, config_compliance,
                config_venture_facts, status, admin_magic_link_token, kernel_version
            )
            VALUES ($1, $2, $3, $4, $5::uuid, $6, $7, $8::jsonb, $9, $10, 'spawning', $11::uuid, 'v3.0.0')
            ON CONFLICT (student_id) DO UPDATE SET
                config_voice_profile = EXCLUDED.config_voice_profile,
                config_style_rules = EXCLUDED.config_style_rules,
                config_story_pool = EXCLUDED.config_story_pool,
                config_compliance = EXCLUDED.config_compliance,
                config_venture_facts = EXCLUDED.config_venture_facts,
                status = 'spawning',
                updated_at = NOW()
        """, student_id, subdomain, custom_domain,
            f"{student_id}.fan.breakout.live",
            fan_hub_tenant_id,
            configs["voice_profile.md"], configs["style_rules.md"],
            configs["story_pool.json"], configs["compliance.yaml"],
            configs["venture_facts.yaml"],
            magic_link_token)

        result.subdomain = subdomain
        result.custom_domain = primary_domain

    finally:
        await conn.close()

    # Step 5: Spawn Railway service
    railway_service = await _spawn_railway_service(student_id, configs)
    if railway_service.get("error"):
        result.errors.append(f"Railway spawn fail: {railway_service['error']}")
        result.next_steps.append("Manual fallback: Anna fork repo + deploy via Railway dashboard")
        return result

    result.railway_service_id = railway_service.get("service_id")
    result.railway_service_name = railway_service.get("service_name")

    # Step 6: Wait health (skipped in skeleton - manual verify)
    result.next_steps.append("Wait 3-5 min for Railway service health, verify at admin URL")

    # Step 7: CNAME
    if not custom_domain:
        cname_ok = await _create_aios_cname(student_id, railway_service.get("railway_url", ""))
        result.cname_created = cname_ok
        if not cname_ok:
            result.errors.append("CNAME failed - Anna setup manual in Cloudflare dashboard")
            result.next_steps.append(f"Add CNAME `{student_id}.aios` → `{railway_service.get('railway_url')}` proxied=False")

    # Step 8: Send email
    result.admin_url = f"https://{primary_domain}/admin?token={magic_link_token}"
    email_ok = await _send_capstone_email(owner_email, display_name, result.admin_url, primary_domain)
    result.email_sent = email_ok
    if not email_ok:
        result.errors.append("Email send failed - Anna gửi manual")
        result.next_steps.append(f"Anna copy admin URL gửi cho student: {result.admin_url}")

    result.success = len(result.errors) == 0
    return result


# ─────────────────────────────────────────────────────────────
# Helpers (Railway + Cloudflare + Brevo)
# ─────────────────────────────────────────────────────────────

async def _spawn_railway_service(student_id: str, configs: dict) -> dict:
    """Spawn Railway service from template.

    PLACEHOLDER trong skeleton này. Anna setup actual Railway template repo trước:
        1. Fork cohangai-camas-kernel → cohangai-camas-kernel-template
        2. Strip Anna config (5 files), thay placeholder
        3. Setup Railway template at railway.app/templates/...
        4. Configure RAILWAY_API_TOKEN env

    Sau khi Anna setup:
        Replace return placeholder bằng actual Railway API call.

    Hiện trả về placeholder + log.
    """
    log.warning(
        f"[PLACEHOLDER] Railway spawn for {student_id} not implemented. "
        f"Anna setup template repo trước. Configs saved DB, ready to deploy manual."
    )
    return {
        "error": None,
        "service_id": f"capstone-{student_id}-placeholder",
        "service_name": f"camas-kernel-{student_id}",
        "railway_url": f"camas-kernel-{student_id}-production.up.railway.app",
        "status": "placeholder",
        "note": "Manual Railway deploy required until template repo ready"
    }


async def _create_aios_cname(student_id: str, target: str) -> bool:
    """Create CNAME {student_id}.aios.breakout.live → target Railway URL."""
    if httpx is None:
        return False

    token = os.environ.get("CLOUDFLARE_API_TOKEN")
    zone_id = os.environ.get("CLOUDFLARE_ZONE_ID_BREAKOUT")
    if not token or not zone_id:
        log.warning("Cloudflare creds missing, skip CNAME")
        return False

    url = f"https://api.cloudflare.com/client/v4/zones/{zone_id}/dns_records"
    payload = {
        "type": "CNAME",
        "name": f"{student_id}.aios",
        "content": target,
        "ttl": 300,
        "proxied": False
    }

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(url, json=payload, headers={"Authorization": f"Bearer {token}"})
        if resp.status_code == 200:
            return True
        log.warning(f"Cloudflare CNAME failed {resp.status_code}: {resp.text[:200]}")
        return False


async def _send_capstone_email(to_email: str, display_name: str, admin_url: str, domain: str) -> bool:
    """Send Capstone graduation email với admin URL + welcome."""
    if httpx is None:
        return False

    key = os.environ.get("BREVO_API_KEY")
    if not key:
        return False

    subject = "BreakoutOS Capstone của bạn đã sẵn sàng"
    html = f"""
    <p>Chào {display_name},</p>
    <p>BreakoutOS instance riêng của bạn đã spawn thành công.</p>
    <p><strong>Truy cập admin:</strong></p>
    <p><a href="{admin_url}" style="background:#ED1C24;color:#fff;padding:14px 28px;text-decoration:none;border-radius:4px;display:inline-block">Mở BreakoutOS Admin</a></p>
    <p>Domain: <code>{domain}</code></p>
    <p>Trong instance này bạn có:</p>
    <ul>
        <li>7 trợ lý AI đã huấn luyện trên dữ liệu của bạn</li>
        <li>1 Fan Hub riêng lưu mọi khách hàng</li>
        <li>1 AI COO báo cáo mỗi sáng 6am</li>
        <li>Lifetime kernel update (auto mỗi tháng)</li>
    </ul>
    <p>Đào Thị Hằng</p>
    """

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            "https://api.brevo.com/v3/smtp/email",
            json={
                "sender": {"name": "Đào Thị Hằng", "email": "support@daothihang.com"},
                "to": [{"email": to_email, "name": display_name}],
                "subject": subject,
                "htmlContent": html,
                "replyTo": {"email": "support@daothihang.com"}
            },
            headers={"api-key": key, "content-type": "application/json"}
        )
        return resp.status_code in (200, 201, 202)


# ─────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Spawn BreakoutOS Capstone AIOS instance")
    parser.add_argument("--student-id", required=True)
    parser.add_argument("--owner-email", required=True)
    parser.add_argument("--display-name", required=True)
    parser.add_argument("--venture-slug", default="breakout")
    parser.add_argument("--custom-domain", default=None)
    parser.add_argument("--data-file", required=True, help="Path to JSON file with student_data")
    parser.add_argument("--dry-run", action="store_true", help="Generate configs only, no Railway spawn")

    args = parser.parse_args()

    with open(args.data_file) as f:
        student_data = json.load(f)

    result = asyncio.run(spawn_capstone_instance(
        student_id=args.student_id,
        owner_email=args.owner_email,
        display_name=args.display_name,
        student_data=student_data,
        venture_slug=args.venture_slug,
        custom_domain=args.custom_domain,
        dry_run=args.dry_run,
    ))

    print(json.dumps(asdict(result), indent=2, default=str))

    if not result.success:
        sys.exit(1)


if __name__ == "__main__":
    main()
